"""
padas.py — GENERATED FILE. Do not edit by hand.

Source: KB section 25 of COSMIC_PDF_AUGMENTATION_TEXT in agents/prompts/cosmic_prompts.py
Regenerate: python tools/extract_cosmic_kb.py

Content is verbatim from the knowledge base. To change a mapping, edit the KB and regenerate,
so the prompt text and the engine data can never disagree.
"""


PADA_SUBSECTOR = {
    (0, 1): {
        'kb_label': 'Ashwini P1',
        'nakshatra': 'Ashwini',
        'names': ['Poly Medicure', 'Bharat Forge defense', 'MTAR Tech'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Aries',
        'sign': 'Aries',
        'sub_sector': 'Emergency/surgical pharma, ambulance/EMS, defense small-caps, military hardware, contract logistics',
    },
    (0, 2): {
        'kb_label': 'Ashwini P2',
        'nakshatra': 'Ashwini',
        'names': ['HUL', 'Honasa Consumer', 'P&G Hygiene'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Taurus',
        'sign': 'Aries',
        'sub_sector': 'Cosmetic/aesthetic medicine, FMCG personal care, dermatology, luxury wellness',
    },
    (0, 3): {
        'kb_label': 'Ashwini P3',
        'nakshatra': 'Ashwini',
        'names': ['Apollo Hospitals', 'Practo', 'Tata Elxsi healthcare'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Gemini',
        'sign': 'Aries',
        'sub_sector': 'Telemedicine, healthtech, diagnostic AI, medical devices software',
    },
    (0, 4): {
        'kb_label': 'Ashwini P4',
        'nakshatra': 'Ashwini',
        'names': ['Nestle India', 'Mead Johnson'],
        'navamsa_lord': 'Moon',
        'navamsa_sign': 'Cancer',
        'sign': 'Aries',
        'sub_sector': 'Pediatric care, maternal health, hydration/nutrition, dairy pharma',
    },
    (1, 1): {
        'kb_label': 'Bharani P1',
        'nakshatra': 'Bharani',
        'names': ['Max Healthcare', 'Apollo', 'AIIMS partnerships'],
        'navamsa_lord': 'Sun',
        'navamsa_sign': 'Leo',
        'sign': 'Aries',
        'sub_sector': 'Cardiology, premium hospitals, govt healthcare schemes',
    },
    (1, 2): {
        'kb_label': 'Bharani P2',
        'nakshatra': 'Bharani',
        'names': ['Divis Lab', 'Laurus Labs', 'Syngene'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Virgo',
        'sign': 'Aries',
        'sub_sector': 'API/CDMO manufacturing, generic drug exports, contract research',
    },
    (1, 3): {
        'kb_label': 'Bharani P3',
        'nakshatra': 'Bharani',
        'names': ['Mankind Pharma', 'Nykaa'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Libra',
        'sign': 'Aries',
        'sub_sector': 'Beauty pharma, cosmeceuticals, wellness retail, aesthetic clinics',
    },
    (1, 4): {
        'kb_label': 'Bharani P4',
        'nakshatra': 'Bharani',
        'names': ['Sun Pharma oncology', 'HCG', 'Poly Medicure'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Scorpio',
        'sign': 'Aries',
        'sub_sector': 'Oncology, surgical instruments, military medical, forensic',
    },
    (2, 1): {
        'kb_label': 'Krittika P1',
        'nakshatra': 'Krittika',
        'names': ['Patanjali', 'Apollo educational ventures'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Sagittarius',
        'sign': 'Aries',
        'sub_sector': 'Medical education, hospital chains expansion, faith healing/Ayurveda',
    },
    (2, 2): {
        'kb_label': 'Krittika P2',
        'nakshatra': 'Krittika',
        'names': ['Adani Wilmar', 'Ruchi Soya', 'Marico edible'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Capricorn',
        'sign': 'Taurus',
        'sub_sector': 'Industrial cooking oils, mass FMCG staples, edible oil refining',
    },
    (2, 3): {
        'kb_label': 'Krittika P3',
        'nakshatra': 'Krittika',
        'names': ['Britannia', 'ITC foods', 'Tata Consumer'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Aquarius',
        'sign': 'Taurus',
        'sub_sector': 'Food processing automation, packaged food disruptors, alt-protein',
    },
    (2, 4): {
        'kb_label': 'Krittika P4',
        'nakshatra': 'Krittika',
        'names': ['Amul', 'Mother Dairy', 'Hatsun Agro'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Pisces',
        'sign': 'Taurus',
        'sub_sector': 'Religious/cultural FMCG, ghee, dairy export, premium oils',
    },
    (3, 1): {
        'kb_label': 'Rohini P1',
        'nakshatra': 'Rohini',
        'names': ['Nestle Maggi protein', 'Amul whey', 'Optimum'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Aries',
        'sign': 'Taurus',
        'sub_sector': 'Sports nutrition, energy drinks, protein supplements',
    },
    (3, 2): {
        'kb_label': 'Rohini P2',
        'nakshatra': 'Rohini',
        'names': ['Hatsun', 'Mondelez India', 'ITC Fabelle'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Taurus',
        'sign': 'Taurus',
        'sub_sector': 'Premium dairy, luxury chocolates, gourmet',
    },
    (3, 3): {
        'kb_label': 'Rohini P3',
        'nakshatra': 'Rohini',
        'names': ['Zomato Blinkit', 'Swiggy Instamart', 'Tata BigBasket'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Gemini',
        'sign': 'Taurus',
        'sub_sector': 'Quick-commerce groceries, e-grocery, food delivery',
    },
    (3, 4): {
        'kb_label': 'Rohini P4',
        'nakshatra': 'Rohini',
        'names': ['Nestle Cerelac', 'Britannia bread'],
        'navamsa_lord': 'Moon',
        'navamsa_sign': 'Cancer',
        'sign': 'Taurus',
        'sub_sector': 'Milk products, breakfast cereals, baby food',
    },
    (4, 1): {
        'kb_label': 'Mrigashira P1',
        'nakshatra': 'Mrigashira',
        'names': ['Indian Hotels', 'EIH', 'ITC Hotels'],
        'navamsa_lord': 'Sun',
        'navamsa_sign': 'Leo',
        'sign': 'Taurus',
        'sub_sector': 'Premium hospitality, palace hotels, govt-backed tourism',
    },
    (4, 2): {
        'kb_label': 'Mrigashira P2',
        'nakshatra': 'Mrigashira',
        'names': ['EaseMyTrip', 'Yatra', 'IxiGo'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Virgo',
        'sign': 'Taurus',
        'sub_sector': 'Hotel-tech, OYO-style aggregators, travel SaaS',
    },
    (4, 3): {
        'kb_label': 'Mrigashira P3',
        'nakshatra': 'Mrigashira',
        'names': ['Bharti Airtel', 'Reliance Jio', 'Tata Play'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Libra',
        'sign': 'Gemini',
        'sub_sector': 'Premium telecom plans, broadband for affluent, OTT subscriptions',
    },
    (4, 4): {
        'kb_label': 'Mrigashira P4',
        'nakshatra': 'Mrigashira',
        'names': ['BEL', 'BDL', 'Tata Elxsi defense'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Scorpio',
        'sign': 'Gemini',
        'sub_sector': 'Defense electronics, surveillance tech, signal intelligence',
    },
    (5, 1): {
        'kb_label': 'Ardra P1',
        'nakshatra': 'Ardra',
        'names': ['Infosys Finacle', 'TCS BaNCS', 'PayTM'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Sagittarius',
        'sign': 'Gemini',
        'sub_sector': 'Banking IT systems, fintech infrastructure, payment rails',
    },
    (5, 2): {
        'kb_label': 'Ardra P2',
        'nakshatra': 'Ardra',
        'names': ['Indus Towers', 'ATC', 'Tata Comm DC'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Capricorn',
        'sign': 'Gemini',
        'sub_sector': 'Telecom towers/infrastructure, fiber optics, data centers',
    },
    (5, 3): {
        'kb_label': 'Ardra P3',
        'nakshatra': 'Ardra',
        'names': ['Persistent Systems', 'Tata Tech', 'Zoho'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Aquarius',
        'sign': 'Gemini',
        'sub_sector': 'SaaS platforms, cloud computing, AI infrastructure',
    },
    (5, 4): {
        'kb_label': 'Ardra P4',
        'nakshatra': 'Ardra',
        'names': ['Zee', 'PVR Inox', 'Saregama'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Pisces',
        'sign': 'Gemini',
        'sub_sector': 'Media/film tech, streaming platforms, content IP',
    },
    (6, 1): {
        'kb_label': 'Punarvasu P1',
        'nakshatra': 'Punarvasu',
        'names': ['Delhivery', 'Mahindra Logistics', 'TCI'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Aries',
        'sign': 'Gemini',
        'sub_sector': 'Logistics, road freight, last-mile delivery',
    },
    (6, 2): {
        'kb_label': 'Punarvasu P2',
        'nakshatra': 'Punarvasu',
        'names': ['Nykaa', 'FirstCry', 'Mamaearth'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Taurus',
        'sign': 'Gemini',
        'sub_sector': 'E-commerce, retail tech, D2C consumer brands',
    },
    (6, 3): {
        'kb_label': 'Punarvasu P3',
        'nakshatra': 'Punarvasu',
        'names': ['TCS', 'Infosys', 'Wipro', 'HCL'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Gemini',
        'sign': 'Gemini',
        'sub_sector': 'Pure IT services, BPO, knowledge process outsourcing',
    },
    (6, 4): {
        'kb_label': 'Punarvasu P4',
        'nakshatra': 'Punarvasu',
        'names': ['Nestle India', 'ITC FMCG', 'HUL'],
        'navamsa_lord': 'Moon',
        'navamsa_sign': 'Cancer',
        'sign': 'Cancer',
        'sub_sector': 'Dairy giants, water utilities, urban consumer staples',
    },
    (7, 1): {
        'kb_label': 'Pushya P1',
        'nakshatra': 'Pushya',
        'names': ['SBI', 'LIC', 'Bank of Baroda'],
        'navamsa_lord': 'Sun',
        'navamsa_sign': 'Leo',
        'sign': 'Cancer',
        'sub_sector': 'Govt-backed banking, public sector insurance, sovereign deposits',
    },
    (7, 2): {
        'kb_label': 'Pushya P2',
        'nakshatra': 'Pushya',
        'names': ['HDFC Bank', 'Bajaj Finance', 'Chola Finance'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Virgo',
        'sign': 'Cancer',
        'sub_sector': 'Private banking, NBFC lending, MFI sector',
    },
    (7, 3): {
        'kb_label': 'Pushya P3',
        'nakshatra': 'Pushya',
        'names': ['360 ONE', 'ICICI Pru', 'Nuvama'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Libra',
        'sign': 'Cancer',
        'sub_sector': 'Premium wealth management, fee-based asset mgmt, family offices',
    },
    (7, 4): {
        'kb_label': 'Pushya P4',
        'nakshatra': 'Pushya',
        'names': ['HDFC Life', 'ICICI Lombard', 'SBI Life'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Scorpio',
        'sign': 'Cancer',
        'sub_sector': 'Insurance (general/life), claims processing, reinsurance',
    },
    (8, 1): {
        'kb_label': 'Ashlesha P1',
        'nakshatra': 'Ashlesha',
        'names': ['HDFC AMC', 'Nippon Life AMC', 'UTI'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Sagittarius',
        'sign': 'Cancer',
        'sub_sector': 'Mutual funds, AMCs, retirement planning',
    },
    (8, 2): {
        'kb_label': 'Ashlesha P2',
        'nakshatra': 'Ashlesha',
        'names': ['DLF', 'Macrotech', 'LIC Housing'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Capricorn',
        'sign': 'Cancer',
        'sub_sector': 'Real estate (residential mid-cap), housing finance',
    },
    (8, 3): {
        'kb_label': 'Ashlesha P3',
        'nakshatra': 'Ashlesha',
        'names': ['Cipla', "Dr. Reddy's", 'Lupin'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Aquarius',
        'sign': 'Cancer',
        'sub_sector': 'Pharma generics in chronic care, biosimilars',
    },
    (8, 4): {
        'kb_label': 'Ashlesha P4',
        'nakshatra': 'Ashlesha',
        'names': ['Fortis', 'Manipal', 'Aster DM'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Pisces',
        'sign': 'Cancer',
        'sub_sector': 'Hospital chains specializing in psychiatric/neuro',
    },
    (9, 1): {
        'kb_label': 'Magha P1',
        'nakshatra': 'Magha',
        'names': ['HAL', 'BEL', 'BDL', 'Mishra Dhatu'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Aries',
        'sign': 'Leo',
        'sub_sector': 'Defense PSUs, weapons manufacturing, military exports',
    },
    (9, 2): {
        'kb_label': 'Magha P2',
        'nakshatra': 'Magha',
        'names': ['Titan', 'Kalyan Jewellers', 'PC Jeweller'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Taurus',
        'sign': 'Leo',
        'sub_sector': 'Luxury jewelry, premium gold retail, designer brands',
    },
    (9, 3): {
        'kb_label': 'Magha P3',
        'nakshatra': 'Magha',
        'names': ['Wipro govt', 'TCS public sector'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Gemini',
        'sign': 'Leo',
        'sub_sector': 'Govt IT contracts, e-governance platforms, UIDAI tech',
    },
    (9, 4): {
        'kb_label': 'Magha P4',
        'nakshatra': 'Magha',
        'names': ['PNB', 'Union Bank', 'Indian Bank'],
        'navamsa_lord': 'Moon',
        'navamsa_sign': 'Cancer',
        'sign': 'Leo',
        'sub_sector': 'PSU banks (mid-tier), regional/cooperative banking',
    },
    (10, 1): {
        'kb_label': 'P.Phalguni P1',
        'nakshatra': 'Purva Phalguni',
        'names': ['Reliance Jio Cinema', 'Disney+ Hotstar'],
        'navamsa_lord': 'Sun',
        'navamsa_sign': 'Leo',
        'sign': 'Leo',
        'sub_sector': 'Premium media, OTT, entertainment giants',
    },
    (10, 2): {
        'kb_label': 'P.Phalguni P2',
        'nakshatra': 'Purva Phalguni',
        'names': ['PVR Inox', 'Cinepolis India'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Virgo',
        'sign': 'Leo',
        'sub_sector': 'Cinema chains, multiplexes, exhibition',
    },
    (10, 3): {
        'kb_label': 'P.Phalguni P3',
        'nakshatra': 'Purva Phalguni',
        'names': ['Indian Hotels weddings', 'Wedmegood'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Libra',
        'sign': 'Leo',
        'sub_sector': 'Wedding industry, event mgmt, luxury hospitality',
    },
    (10, 4): {
        'kb_label': 'P.Phalguni P4',
        'nakshatra': 'Purva Phalguni',
        'names': ['Dream11', 'Nazara', 'Delta Corp'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Scorpio',
        'sign': 'Leo',
        'sub_sector': 'Sports leagues, gaming, fantasy sports',
    },
    (11, 1): {
        'kb_label': 'U.Phalguni P1',
        'nakshatra': 'Uttara Phalguni',
        'names': ['PhysicsWallah', 'Veranda', 'Aakash'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Sagittarius',
        'sign': 'Leo',
        'sub_sector': 'Education tech, premium coaching, edtech IPO names',
    },
    (11, 2): {
        'kb_label': 'U.Phalguni P2',
        'nakshatra': 'Uttara Phalguni',
        'names': ['KPMG India listed', 'Big4 affiliates'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Capricorn',
        'sign': 'Virgo',
        'sub_sector': 'Audit/consulting firms, advisory services, compliance',
    },
    (11, 3): {
        'kb_label': 'U.Phalguni P3',
        'nakshatra': 'Uttara Phalguni',
        'names': ['LTIMindtree', 'Mphasis', 'Cyient'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Aquarius',
        'sign': 'Virgo',
        'sub_sector': 'Tech disruption analytics, big data services',
    },
    (11, 4): {
        'kb_label': 'U.Phalguni P4',
        'nakshatra': 'Uttara Phalguni',
        'names': ['Vedanta sustainability arm', 'Tata Power renewable'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Pisces',
        'sign': 'Virgo',
        'sub_sector': 'ESG/sustainability advisory, climate finance',
    },
    (12, 1): {
        'kb_label': 'Hasta P1',
        'nakshatra': 'Hasta',
        'names': ['Honeywell Auto', 'Siemens India', 'Bosch'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Aries',
        'sign': 'Virgo',
        'sub_sector': 'Industrial automation, factory robotics',
    },
    (12, 2): {
        'kb_label': 'Hasta P2',
        'nakshatra': 'Hasta',
        'names': ['PI Industries', 'SRF', 'Pidilite'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Taurus',
        'sign': 'Virgo',
        'sub_sector': 'Specialty chemicals, fine chemicals, fragrance',
    },
    (12, 3): {
        'kb_label': 'Hasta P3',
        'nakshatra': 'Hasta',
        'names': ['Apollo HealthCo', 'Tata 1mg'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Gemini',
        'sign': 'Virgo',
        'sub_sector': 'Healthcare data, EHR systems, hospital IT',
    },
    (12, 4): {
        'kb_label': 'Hasta P4',
        'nakshatra': 'Hasta',
        'names': ['Stelis', 'Antara senior living'],
        'navamsa_lord': 'Moon',
        'navamsa_sign': 'Cancer',
        'sign': 'Virgo',
        'sub_sector': 'Hygiene products, sanitation, eldercare',
    },
    (13, 1): {
        'kb_label': 'Chitra P1',
        'nakshatra': 'Chitra',
        'names': ['L&T', 'KEC International', 'Kalpataru'],
        'navamsa_lord': 'Sun',
        'navamsa_sign': 'Leo',
        'sign': 'Virgo',
        'sub_sector': 'Engineering services, EPC contractors, public infra',
    },
    (13, 2): {
        'kb_label': 'Chitra P2',
        'nakshatra': 'Chitra',
        'names': ['Quess Corp', 'TeamLease', 'SIS'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Virgo',
        'sign': 'Virgo',
        'sub_sector': 'Pure-play consulting, professional services',
    },
    (13, 3): {
        'kb_label': 'Chitra P3',
        'nakshatra': 'Chitra',
        'names': ['Maruti premium', 'Mercedes India', 'Page Industries'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Libra',
        'sign': 'Libra',
        'sub_sector': 'Luxury auto, premium consumer durables, fashion',
    },
    (13, 4): {
        'kb_label': 'Chitra P4',
        'nakshatra': 'Chitra',
        'names': ['Clove Dental', 'VLCC', 'Kaya'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Scorpio',
        'sign': 'Libra',
        'sub_sector': 'Cosmetic surgery, premium dental, aesthetic medicine',
    },
    (14, 1): {
        'kb_label': 'Swati P1',
        'nakshatra': 'Swati',
        'names': ['360 ONE', 'IIFL Wealth', 'ASK Wealth'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Sagittarius',
        'sign': 'Libra',
        'sub_sector': 'Wealth advisory, RIA, family office services',
    },
    (14, 2): {
        'kb_label': 'Swati P2',
        'nakshatra': 'Swati',
        'names': ['Inox Wind', 'Suzlon', 'Adani Green'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Capricorn',
        'sign': 'Libra',
        'sub_sector': 'Wind energy, sustainable infra, green REITs',
    },
    (14, 3): {
        'kb_label': 'Swati P3',
        'nakshatra': 'Swati',
        'names': ['IndiGo', 'SpiceJet', 'Air India unlisted'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Aquarius',
        'sign': 'Libra',
        'sub_sector': 'Aviation, airlines, MRO services',
    },
    (14, 4): {
        'kb_label': 'Swati P4',
        'nakshatra': 'Swati',
        'names': ['Adani Ports', 'JSW Infra', 'Cochin Shipyard'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Pisces',
        'sign': 'Libra',
        'sub_sector': 'International trade, exports/imports, shipping lines',
    },
    (15, 1): {
        'kb_label': 'Vishakha P1',
        'nakshatra': 'Vishakha',
        'names': ['Coca-Cola India', 'PepsiCo India'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Aries',
        'sign': 'Libra',
        'sub_sector': 'Energy drinks, sports beverages',
    },
    (15, 2): {
        'kb_label': 'Vishakha P2',
        'nakshatra': 'Vishakha',
        'names': ['Tanishq', 'Kalyan', 'Joyalukkas'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Taurus',
        'sign': 'Libra',
        'sub_sector': 'Bridal/wedding gold, festival retail',
    },
    (15, 3): {
        'kb_label': 'Vishakha P3',
        'nakshatra': 'Vishakha',
        'names': ['Banking treasury operations'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Gemini',
        'sign': 'Libra',
        'sub_sector': 'Forex/FX trading, currency derivatives, NDF markets',
    },
    (15, 4): {
        'kb_label': 'Vishakha P4',
        'nakshatra': 'Vishakha',
        'names': ['Edelweiss ARC', 'Arcil'],
        'navamsa_lord': 'Moon',
        'navamsa_sign': 'Cancer',
        'sign': 'Scorpio',
        'sub_sector': 'Hidden liquidity (dark pools), private credit, distressed debt',
    },
    (16, 1): {
        'kb_label': 'Anuradha P1',
        'nakshatra': 'Anuradha',
        'names': ['Coal India', 'NMDC', 'MOIL'],
        'navamsa_lord': 'Sun',
        'navamsa_sign': 'Leo',
        'sign': 'Scorpio',
        'sub_sector': 'Govt-backed mining (coal, iron ore PSUs)',
    },
    (16, 2): {
        'kb_label': 'Anuradha P2',
        'nakshatra': 'Anuradha',
        'names': ['Hindustan Copper', 'Vedanta', 'NALCO'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Virgo',
        'sign': 'Scorpio',
        'sub_sector': 'Specialty metals, rare earth, lithium',
    },
    (16, 3): {
        'kb_label': 'Anuradha P3',
        'nakshatra': 'Anuradha',
        'names': ['MMTC', 'Rajesh Exports'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Libra',
        'sign': 'Scorpio',
        'sub_sector': 'Cosmetic/jewelry precious metals (platinum, palladium)',
    },
    (16, 4): {
        'kb_label': 'Anuradha P4',
        'nakshatra': 'Anuradha',
        'names': ['Solar Industries', 'Premier Explosives'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Scorpio',
        'sign': 'Scorpio',
        'sub_sector': 'Defense ammunition, explosives, mining equipment',
    },
    (17, 1): {
        'kb_label': 'Jyeshtha P1',
        'nakshatra': 'Jyeshtha',
        'names': ['ONGC', 'Oil India', 'Reliance E&P'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Sagittarius',
        'sign': 'Scorpio',
        'sub_sector': 'International oil exploration, upstream',
    },
    (17, 2): {
        'kb_label': 'Jyeshtha P2',
        'nakshatra': 'Jyeshtha',
        'names': ['IOC', 'BPCL', 'GAIL'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Capricorn',
        'sign': 'Scorpio',
        'sub_sector': 'Pipeline infra, oil refining, downstream',
    },
    (17, 3): {
        'kb_label': 'Jyeshtha P3',
        'nakshatra': 'Jyeshtha',
        'names': ['Reliance petchem', 'GAIL', 'Deepak Nitrite'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Aquarius',
        'sign': 'Scorpio',
        'sub_sector': 'Petrochemicals, plastics, polymer',
    },
    (17, 4): {
        'kb_label': 'Jyeshtha P4',
        'nakshatra': 'Jyeshtha',
        'names': ['Petronet LNG', 'Indraprastha Gas', 'MGL'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Pisces',
        'sign': 'Scorpio',
        'sub_sector': 'LNG, gas import terminals, city gas',
    },
    (18, 1): {
        'kb_label': 'Mula P1',
        'nakshatra': 'Mula',
        'names': ['HAL', 'BDL', 'MTAR Tech'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Aries',
        'sign': 'Sagittarius',
        'sub_sector': 'Defense aviation, fighter aircraft, missiles',
    },
    (18, 2): {
        'kb_label': 'Mula P2',
        'nakshatra': 'Mula',
        'names': ['Indian Hotels', 'EIH', 'Lemon Tree premium'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Taurus',
        'sign': 'Sagittarius',
        'sub_sector': 'Luxury hotels (5-star+), spa/wellness retreats',
    },
    (18, 3): {
        'kb_label': 'Mula P3',
        'nakshatra': 'Mula',
        'names': ['NIIT', 'Career Point', 'Aakash', 'AbroAd'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Gemini',
        'sign': 'Sagittarius',
        'sub_sector': 'Higher education, study-abroad, ed-finance',
    },
    (18, 4): {
        'kb_label': 'Mula P4',
        'nakshatra': 'Mula',
        'names': ['Easy Trip', 'MakeMyTrip'],
        'navamsa_lord': 'Moon',
        'navamsa_sign': 'Cancer',
        'sign': 'Sagittarius',
        'sub_sector': 'Religious tourism, pilgrimage infra, temple economies',
    },
    (19, 1): {
        'kb_label': 'P.Ashadha P1',
        'nakshatra': 'Purva Ashadha',
        'names': ['SIDBI', 'NABARD', 'EXIM Bank (listed associates)'],
        'navamsa_lord': 'Sun',
        'navamsa_sign': 'Leo',
        'sign': 'Sagittarius',
        'sub_sector': 'Govt-backed lending, development banking',
    },
    (19, 2): {
        'kb_label': 'P.Ashadha P2',
        'nakshatra': 'Purva Ashadha',
        'names': ['MyAdvocate', 'vCFO services'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Virgo',
        'sign': 'Sagittarius',
        'sub_sector': 'Legal-tech, regtech, compliance SaaS',
    },
    (19, 3): {
        'kb_label': 'P.Ashadha P3',
        'nakshatra': 'Purva Ashadha',
        'names': ['Reliance Brands', 'Aditya Birla Fashion premium'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Libra',
        'sign': 'Sagittarius',
        'sub_sector': 'International luxury, premium imports, designer retail',
    },
    (19, 4): {
        'kb_label': 'P.Ashadha P4',
        'nakshatra': 'Purva Ashadha',
        'names': ['BEL exports', 'BDL exports'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Scorpio',
        'sign': 'Sagittarius',
        'sub_sector': 'International arms trade, defense exports',
    },
    (20, 1): {
        'kb_label': 'U.Ashadha P1',
        'nakshatra': 'Uttara Ashadha',
        'names': ['HDFC Bank', 'ICICI Bank', 'SBI'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Sagittarius',
        'sign': 'Sagittarius',
        'sub_sector': 'Banking large-caps, AAA-rated corp credit',
    },
    (20, 2): {
        'kb_label': 'U.Ashadha P2',
        'nakshatra': 'Uttara Ashadha',
        'names': ['L&T', 'GMR Infra', 'Adani Ports'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Capricorn',
        'sign': 'Capricorn',
        'sub_sector': 'Heavy infra (ports, roads, bridges)',
    },
    (20, 3): {
        'kb_label': 'U.Ashadha P3',
        'nakshatra': 'Uttara Ashadha',
        'names': ['NTPC', 'Adani Power', 'Tata Power thermal'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Aquarius',
        'sign': 'Capricorn',
        'sub_sector': 'Power generation (thermal coal-based)',
    },
    (20, 4): {
        'kb_label': 'U.Ashadha P4',
        'nakshatra': 'Uttara Ashadha',
        'names': ['NHPC', 'SJVN', 'JSW Hydro'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Pisces',
        'sign': 'Capricorn',
        'sub_sector': 'Hydropower, large dams, water infra',
    },
    (21, 1): {
        'kb_label': 'Shravana P1',
        'nakshatra': 'Shravana',
        'names': ['Tata Steel', 'JSW Steel', 'Jindal Steel'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Aries',
        'sign': 'Capricorn',
        'sub_sector': 'Steel/iron ore mining, ferro-alloys',
    },
    (21, 2): {
        'kb_label': 'Shravana P2',
        'nakshatra': 'Shravana',
        'names': ['UltraTech', 'Shree Cement', 'Kajaria'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Taurus',
        'sign': 'Capricorn',
        'sub_sector': 'Cement, building materials, sanitaryware',
    },
    (21, 3): {
        'kb_label': 'Shravana P3',
        'nakshatra': 'Shravana',
        'names': ['Adani Logistics', 'Mahindra Logistics tech'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Gemini',
        'sign': 'Capricorn',
        'sub_sector': 'Logistics infra, ports IT, supply chain SaaS',
    },
    (21, 4): {
        'kb_label': 'Shravana P4',
        'nakshatra': 'Shravana',
        'names': ['VA Tech Wabag', 'Triveni Engineering'],
        'navamsa_lord': 'Moon',
        'navamsa_sign': 'Cancer',
        'sign': 'Capricorn',
        'sub_sector': 'Water/sewage utilities, hygiene infra',
    },
    (22, 1): {
        'kb_label': 'Dhanishtha P1',
        'nakshatra': 'Dhanishta',
        'names': ['NTPC', 'ONGC', 'IOC', 'SAIL'],
        'navamsa_lord': 'Sun',
        'navamsa_sign': 'Leo',
        'sign': 'Capricorn',
        'sub_sector': 'Govt PSUs (heavyweight), Maharatna stocks',
    },
    (22, 2): {
        'kb_label': 'Dhanishtha P2',
        'nakshatra': 'Dhanishta',
        'names': ['ABB India', 'Honeywell Auto', 'Bosch'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Virgo',
        'sign': 'Capricorn',
        'sub_sector': 'Industrial automation, factory IoT',
    },
    (22, 3): {
        'kb_label': 'Dhanishtha P3',
        'nakshatra': 'Dhanishta',
        'names': ['Adani Green', 'Tata Power Renewable', 'Inox Wind'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Libra',
        'sign': 'Aquarius',
        'sub_sector': 'Renewable energy, solar/wind tech',
    },
    (22, 4): {
        'kb_label': 'Dhanishtha P4',
        'nakshatra': 'Dhanishta',
        'names': ['NPCIL associates', 'Uranium Corp'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Scorpio',
        'sign': 'Aquarius',
        'sub_sector': 'Nuclear power, atomic energy, uranium',
    },
    (23, 1): {
        'kb_label': 'Shatabhisha P1',
        'nakshatra': 'Shatabhisha',
        'names': ['PFC', 'REC', 'IREDA', 'IIFCL'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Sagittarius',
        'sign': 'Aquarius',
        'sub_sector': 'Power finance, IREDA, REC, PFC',
    },
    (23, 2): {
        'kb_label': 'Shatabhisha P2',
        'nakshatra': 'Shatabhisha',
        'names': ['Power Grid', 'Tata Power transmission'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Capricorn',
        'sign': 'Aquarius',
        'sub_sector': 'Transmission grids, power infra',
    },
    (23, 3): {
        'kb_label': 'Shatabhisha P3',
        'nakshatra': 'Shatabhisha',
        'names': ['Torrent Power', 'CESC', 'JSW Energy'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Aquarius',
        'sign': 'Aquarius',
        'sub_sector': 'Pure-play utilities, electricity distribution',
    },
    (23, 4): {
        'kb_label': 'Shatabhisha P4',
        'nakshatra': 'Shatabhisha',
        'names': ['Bharat Biotech (associates)', 'Biocon', 'Panacea'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Pisces',
        'sign': 'Aquarius',
        'sub_sector': 'Pharma R&D (vaccines, biotech)',
    },
    (24, 1): {
        'kb_label': 'P.Bhadra P1',
        'nakshatra': 'Purva Bhadrapada',
        'names': ['Tata Motors EV', 'Ola Electric', 'Exide'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Aries',
        'sign': 'Aquarius',
        'sub_sector': 'EV manufacturing, battery tech',
    },
    (24, 2): {
        'kb_label': 'P.Bhadra P2',
        'nakshatra': 'Purva Bhadrapada',
        'names': ['Tata Motors Nexon EV', 'Mahindra premium EV'],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Taurus',
        'sign': 'Aquarius',
        'sub_sector': 'EV-luxury, premium electric auto',
    },
    (24, 3): {
        'kb_label': 'P.Bhadra P3',
        'nakshatra': 'Purva Bhadrapada',
        'names': ['CoinDCX (private)', 'Zerodha (private)', 'Paytm crypto'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Gemini',
        'sign': 'Aquarius',
        'sub_sector': 'Crypto/blockchain exposure, fintech disruptors',
    },
    (24, 4): {
        'kb_label': 'P.Bhadra P4',
        'nakshatra': 'Purva Bhadrapada',
        'names': ['Great Eastern Shipping', 'Shipping Corp of India', 'GE Shipping'],
        'navamsa_lord': 'Moon',
        'navamsa_sign': 'Cancer',
        'sign': 'Pisces',
        'sub_sector': 'Maritime shipping, ocean logistics',
    },
    (25, 1): {
        'kb_label': 'U.Bhadra P1',
        'nakshatra': 'Uttara Bhadrapada',
        'names': ['Patanjali', 'Sri Mandir', 'ISKCON-affiliated'],
        'navamsa_lord': 'Sun',
        'navamsa_sign': 'Leo',
        'sign': 'Pisces',
        'sub_sector': 'Religious institutions, faith economy, temple bonds',
    },
    (25, 2): {
        'kb_label': 'U.Bhadra P2',
        'nakshatra': 'Uttara Bhadrapada',
        'names': ['Syngene', 'Aurobindo R&D', 'Glenmark R&D'],
        'navamsa_lord': 'Mercury',
        'navamsa_sign': 'Virgo',
        'sign': 'Pisces',
        'sub_sector': 'Pharmaceutical R&D, drug discovery, contract research',
    },
    (25, 3): {
        'kb_label': 'U.Bhadra P3',
        'nakshatra': 'Uttara Bhadrapada',
        'names': ['Honasa', 'Nykaa', "L'Oreal India"],
        'navamsa_lord': 'Venus',
        'navamsa_sign': 'Libra',
        'sign': 'Pisces',
        'sub_sector': 'Beauty/cosmetics, perfumes, luxury skincare',
    },
    (25, 4): {
        'kb_label': 'U.Bhadra P4',
        'nakshatra': 'Uttara Bhadrapada',
        'names': ['Linde India', 'INOX Air Products'],
        'navamsa_lord': 'Mars',
        'navamsa_sign': 'Scorpio',
        'sign': 'Pisces',
        'sub_sector': 'Chemical warfare, hazmat, industrial gases',
    },
    (26, 1): {
        'kb_label': 'Revati P1',
        'nakshatra': 'Revati',
        'names': ['State Bank of India intl', 'ICICI Bank intl'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Sagittarius',
        'sign': 'Pisces',
        'sub_sector': 'International banking, FX, trade finance',
    },
    (26, 2): {
        'kb_label': 'Revati P2',
        'nakshatra': 'Revati',
        'names': ['Avanti Feeds', 'Apex Frozen Foods'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Capricorn',
        'sign': 'Pisces',
        'sub_sector': 'Marine infra, fishing fleet, aquaculture',
    },
    (26, 3): {
        'kb_label': 'Revati P3',
        'nakshatra': 'Revati',
        'names': ['VA Tech Wabag', 'Ion Exchange'],
        'navamsa_lord': 'Saturn',
        'navamsa_sign': 'Aquarius',
        'sign': 'Pisces',
        'sub_sector': 'Water treatment, desalination, sewage',
    },
    (26, 4): {
        'kb_label': 'Revati P4',
        'nakshatra': 'Revati',
        'names': ['Patanjali', 'Dabur', 'Emami'],
        'navamsa_lord': 'Jupiter',
        'navamsa_sign': 'Pisces',
        'sign': 'Pisces',
        'sub_sector': 'Pure spiritual/wellness economy, meditation tech, ayurveda exports',
    },
}
